### ISSUE TITLE
Get LOCAL IP in Windows and MacOS

### ISSUE THREAD

**Issue by LiveRock** [AgnelSelvan/wifi_ip_details#2]
Currently, I am getting public IP address back from 

`_ipDetails = await WifiIPDetails.getMyWIFIDetails();`

Is it possible to get the **LOCAL IP address** like 192.168.1.1 ?

**Comment by AgnelSelvan** [comment]
Hello @LiveRock, you can try using `NetworkInterface` for getting **LOCAL IP Address**
